// Posts
export const LOAD_POSTS_REQUEST = 'LOAD_POSTS_REQUEST'
export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS'
export const LOAD_POSTS_FAILURE = 'LOAD_POSTS_FAILURE'

// Single Post
export const LOAD_POST_REQUEST = 'LOAD_POST_REQUEST'
export const LOAD_POST_SUCCESS = 'LOAD_POST_SUCCESS'
export const LOAD_POST_FAILURE = 'LOAD_POST_FAILURE'

// Masonry
export const LOAD_MASONRY_REQUEST = 'LOAD_MASONRY_REQUEST'
export const LOAD_MASONRY_SUCCESS = 'LOAD_MASONRY_SUCCESS'
export const LOAD_MASONRY_FAILURE = 'LOAD_MASONRY_FAILURE'
export const SET_LOADING_IMAGES = 'SET_LOADING_IMAGES'
export const POS_IMAGE = 'POS_IMAGE'
export const IMAGE_LOADED = 'IMAGE_LOADED'